INSERT INTO PERSON_ENTITIES (AGE, NAME, SURNAME)
VALUES (18, 'Anna', 'Maria');
INSERT INTO PERSON_ENTITIES (AGE, NAME, SURNAME)
VALUES (25, 'Anton', 'Tamm');
INSERT INTO PERSON_ENTITIES (AGE, NAME, SURNAME)
VALUES (40, 'Eelika', 'Anton');